name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Run Jest tests
        run: |
          yarn test
      - name: Run Cypress tests
        run: |
          yarn cy:run
